name: R-CMD-check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('devtools')"
          Rscript -e "devtools::install_deps(dep=TRUE)"
      - name: Check
        run: R CMD check .
